#it can be done much more beautifully, but it was not required in the task and it is not production.

version: '3.8'
services:

  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "test1"
      MYSQL_USER: "test1"
      MYSQL_PASSWORD: "test1"

  app1:
    restart: always
    build: app/
    environment:
      DB: "Server=db;Database=test1;Uid=test1;Pwd=test1;"
    depends_on:
      - db
  app2:
    restart: always
    build: app/
    environment:
      DB: "Server=db;Database=test1;Uid=test1;Pwd=test1;"
    depends_on:
      - db

  nginx:
    restart: always
    build: nginx/
#    image: test:5000/nginx
    ports:
      - "8066:80"
    depends_on:
      - app1



networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
